### ISSUE TITLE
System.ArgumentOutOfRangeExceptionが発生

### ISSUE THREAD

**Issue by yone098** [bicstone/backlog-notify#107]
# 概要
2023-06-23 深夜から `backlog-notify` にてエラーが発生するようになりました。

私は、以下の設定にて GitHub Actions 上で `Backlog Notify` をプロジェクトで利用しています。

```
name: Backlog Notify
on: push
jobs:
  backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Backlog Notify
        uses: bicstone/backlog-notify@master
        env:
          PROJECT_KEY: XXXXXXXXXXXX
          API_HOST: xxxxxxxxxx.backlog.jp
          API_KEY: ${{ secrets.BACKLOG_API_KEY }}
```

昨夜から、以下のエラーが発生するようになりました。node のバージョンを上げたことが原因だと思われます。
https://github.com/bicstone/backlog-notify/blob/54aa39e85886abc7137e78cc63e6cbbbbf545044/action.yml#L8

```
Download action repository 'bicstone/backlog-notify@master' (SHA:54aa39e85886abc7137e78cc63e6cbbbbf545044)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load bicstone/backlog-notify/master/action.yml
```

プロジェクト側では、現在は `master` ではなく、`v4.0.2` を指定することで問題なく動作しております。

```
uses: bicstone/backlog-notify@v4.0.2
```

確認よろしくお願いします。

**Comment by yone098** [comment]
@bicstone 
すみません、README を確認しましたら、v4 指定となっておりました。
結構昔から、backlog notify を利用しておりまして、バージョン指定を master にしたままになっておりました。
不要でありましたら、issue クローズします。
宜しくお願いします🙇‍♂️

**Comment by bicstone** [comment]
@yone098
ご連絡ありがとうございます。
昨日(2023/06/22)の深夜にリリース前の誤ったプログラムが `master` にマージされてしまっていたためただいまリバートいたしました。
大変お手数をおかけいたしました。

**Comment by yone098** [comment]
@bicstone 対応ありがとうございます！
